<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 81,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '70000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'qegqegqegqeg',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:30:09',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            1 => 
            array (
                'id' => 82,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '80000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'geqgqegqeg',
                'final_price' => '48000000',
                'copen_code' => 'jsxwww',
                'copen_reason' => 'jsxwww',
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:30:57',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            2 => 
            array (
                'id' => 83,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '70003942',
                'payment_method' => 'credit-card',
                'delivery_address' => 'rwhwrhw',
                'final_price' => '70003942',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:31:40',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            3 => 
            array (
                'id' => 84,
                'customer_id' => 2,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '70003942',
                'payment_method' => 'credit-card',
                'delivery_address' => 'rwhwrhw',
                'final_price' => '42002365.2',
                'copen_code' => 'jsxwww',
                'copen_reason' => 'rhwhwh',
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:32:11',
                'updated_at' => '2024-10-16 22:32:11',
            ),
            4 => 
            array (
                'id' => 85,
                'customer_id' => 2,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '35000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'hwrhwrhwr',
                'final_price' => '35000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:33:09',
                'updated_at' => '2024-10-16 22:33:09',
            ),
            5 => 
            array (
                'id' => 87,
                'customer_id' => 2,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '255699999',
                'payment_method' => 'credit-card',
                'delivery_address' => 'tejwejetjrykrykrykrkrykrk',
                'final_price' => '255699999',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:35:05',
                'updated_at' => '2024-10-16 22:35:05',
            ),
            6 => 
            array (
                'id' => 88,
                'customer_id' => 2,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '17099997',
                'payment_method' => 'credit-card',
                'delivery_address' => 'egeqgeggegeeeeeeeeeeeeeeeeeee',
                'final_price' => '15389997.3',
                'copen_code' => 'Takhfif',
                'copen_reason' => 'tretetetete',
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:37:26',
                'updated_at' => '2024-10-16 22:37:26',
            ),
            7 => 
            array (
                'id' => 89,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '70000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'egqeg',
                'final_price' => '63000000',
                'copen_code' => 'Takhfif',
                'copen_reason' => 'qeggqegqegqe',
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:38:00',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            8 => 
            array (
                'id' => 90,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '105000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'fwfwf',
                'final_price' => '105000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 22:38:30',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            9 => 
            array (
                'id' => 98,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'eqgqgqe',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:14:47',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            10 => 
            array (
                'id' => 99,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '40000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'egeqgh',
                'final_price' => '40000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:15:31',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            11 => 
            array (
                'id' => 100,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '200000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'thehthjwetj',
                'final_price' => '60000000',
                'copen_code' => 'test',
                'copen_reason' => 'kjryjuyerjej',
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:17:45',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            12 => 
            array (
                'id' => 103,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'egqegqe',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:20:14',
                'updated_at' => '2024-10-16 23:28:12',
            ),
            13 => 
            array (
                'id' => 105,
                'customer_id' => 2,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '100000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'eqgfqgqeg',
                'final_price' => '30000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:22:54',
                'updated_at' => '2024-10-16 23:22:54',
            ),
            14 => 
            array (
                'id' => 106,
                'customer_id' => 2,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '70000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'qegqg',
                'final_price' => '21000000',
                'copen_code' => 'test',
                'copen_reason' => 'gqegqeg',
                'copen_status' => 1,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:23:49',
                'updated_at' => '2024-10-16 23:23:49',
            ),
            15 => 
            array (
                'id' => 107,
                'customer_id' => 2,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'egqegqg',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:24:27',
                'updated_at' => '2024-10-16 23:24:27',
            ),
            16 => 
            array (
                'id' => 108,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'wrgqgq',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:44:18',
                'updated_at' => '2024-10-16 23:44:18',
            ),
            17 => 
            array (
                'id' => 109,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'wrgqgq',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:44:34',
                'updated_at' => '2024-10-16 23:44:34',
            ),
            18 => 
            array (
                'id' => 110,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'wrgqgq',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:44:49',
                'updated_at' => '2024-10-16 23:44:49',
            ),
            19 => 
            array (
                'id' => 111,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'wrgqgq',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:45:09',
                'updated_at' => '2024-10-16 23:45:09',
            ),
            20 => 
            array (
                'id' => 112,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'wrgqgq',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:45:39',
                'updated_at' => '2024-10-16 23:45:39',
            ),
            21 => 
            array (
                'id' => 113,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '60000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'wrgqgq',
                'final_price' => '60000000',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:45:58',
                'updated_at' => '2024-10-16 23:45:58',
            ),
            22 => 
            array (
                'id' => 114,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '140000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'gqgqegvdvqv',
                'final_price' => '140000000',
                'copen_code' => 'eqgqgqg',
                'copen_reason' => 'qegwqegqeg',
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:47:22',
                'updated_at' => '2024-10-16 23:47:22',
            ),
            23 => 
            array (
                'id' => 115,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '140000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'gqgqegvdvqv',
                'final_price' => '140000000',
                'copen_code' => 'eqgqgqg',
                'copen_reason' => 'qegwqegqeg',
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:48:43',
                'updated_at' => '2024-10-16 23:48:43',
            ),
            24 => 
            array (
                'id' => 116,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '140000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'gqgqegvdvqv',
                'final_price' => '140000000',
                'copen_code' => 'eqgqgqg',
                'copen_reason' => 'qegwqegqeg',
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:49:14',
                'updated_at' => '2024-10-16 23:49:14',
            ),
            25 => 
            array (
                'id' => 117,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '140000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'gqgqegvdvqv',
                'final_price' => '140000000',
                'copen_code' => 'eqgqgqg',
                'copen_reason' => 'qegwqegqeg',
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:53:39',
                'updated_at' => '2024-10-16 23:53:39',
            ),
            26 => 
            array (
                'id' => 118,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '140000000',
                'payment_method' => 'credit-card',
                'delivery_address' => 'gqgqegvdvqv',
                'final_price' => '140000000',
                'copen_code' => 'eqgqgqg',
                'copen_reason' => 'qegwqegqeg',
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:53:57',
                'updated_at' => '2024-10-16 23:53:57',
            ),
            27 => 
            array (
                'id' => 119,
                'customer_id' => 3,
                'discount_id' => 0,
                'order_date' => '2024-10-17 00:00:00',
                'status' => 'pending',
                'total_amount' => '121399998',
                'payment_method' => 'credit-card',
                'delivery_address' => 'gqgqegvdvqv',
                'final_price' => '162799996',
                'copen_code' => NULL,
                'copen_reason' => NULL,
                'copen_status' => 0,
                'star' => NULL,
                'tracking_serial' => NULL,
                'created_at' => '2024-10-16 23:54:11',
                'updated_at' => '2024-10-17 00:04:01',
            ),
        ));
        
        
    }
}